#version 430 

/**
 * Shader updating the selection mask for terrain modifications
 * Compares mouse input with buffer index mapped to world position
 */
layout(local_size_x = 32, local_size_y = 32) in;

layout(std430, binding = 3) buffer SelectionBuffer {
    uint Entries[]; 
} Selection;

uniform ivec2 _TexSize;
uniform ivec3 _WorldSize;
uniform vec3 _WorldPos;
uniform vec3 _BrushPos;
uniform uint _Mode;

void ApplySelection(ivec3 id){
    uint GlobalIndex = id.z * _TexSize.x + id.x;
            
    int BrushSize = 5;
    vec2 BrushUV = (_BrushPos.xz - _WorldPos.xz) / _WorldSize.xz * _TexSize;
    vec2 diff = BrushUV - id.xz;
    float dist2 = dot(diff, diff);
    float d = 1 - dist2 / (BrushSize * BrushSize);
    Selection.Entries[GlobalIndex] += _Mode == 0 ? 0 : uint(d * 255);
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.x, 0, gl_GlobalInvocationID.y);
    ApplySelection(id);
}