#version 430 

#include "TERRAIN_COMMON_SHADER"
/** 
 * Shader updating the heightmap that is used to generate 
 * the actual triangle mesh
 */

#define MODE_APPLY_HEIGHT 0

#define DISPATCH_SIZE 2
layout(local_size_x = DISPATCH_SIZE, local_size_y = DISPATCH_SIZE) in;

// for more layout info see terrainmesh shader
layout(std430, binding = SSBO_LAYOUT_HEIGHTS) buffer HeightBuffer {
    uint Value[]; 
} Heights;

uniform ivec2 _TexSize;
uniform ivec3 _WorldSize;
uniform vec3 _WorldPos;
uniform vec3 _BrushPos;
uniform uint _BrushSize;
uniform int _BrushStrength;
uniform uint _HasSelection;
uniform uint _Mode;

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.x, 0, gl_GlobalInvocationID.y);

    uint GlobalIndex = id.z * _TexSize.x + id.x;
    uint OldValue = Heights.Value[GlobalIndex];

    // get distance to mouse pos, use it as falloff strength
    vec2 BrushUV = (_BrushPos.xz - _WorldPos.xz) / _WorldSize.xz * _TexSize;
    vec2 Dist = BrushUV - id.xz;
    float DistSqr = dot(Dist, Dist);
    float NormDist = 1 - DistSqr / (_BrushSize * _BrushSize);
    NormDist = clamp(NormDist, 0, 1);
    
    uint SelectionValue = Heights.Value[GlobalIndex] >> LAYOUT_SELECTION;
    uint SelectionMask = _HasSelection == 1 ? SelectionValue : uint(round(NormDist));
    
    // has to be int, cause _BrushStrength can be negative
    int NewValue = int(_BrushStrength * SelectionMask);
    uint HeightValue = clamp(int(OldValue & LAYOUT_HEIGHT_MASK) + NewValue, 0, MAX_VALUE) & LAYOUT_HEIGHT_MASK;  
    uint Value = (OldValue & ~LAYOUT_HEIGHT_MASK) + HeightValue;
    
    Heights.Value[GlobalIndex] = Value;
}