#version 430 

#define MODE_COUNT_TRIANGLES 0
#define MODE_GENERATE_TRIANGLES 1
#define MODE_GENERATE_TEX 2
#define MODE_APPLY_SELECTION 3

layout(local_size_x = 32, local_size_y = 32) in;

layout(std430, binding = 0) buffer PositionBuffer {
    vec4 Entries[];
} Positions;

layout(std430, binding = 1) buffer NormalBuffer {
    vec4 Entries[];
} Normals;

layout(std430, binding = 2) buffer CountBuffer {
    uint Count;
} Counter;

layout(std430, binding = 3) buffer SelectionBuffer {
    uint Entries[]; 
} Selection;


layout(binding = 0, rgba16f) uniform image2D Result;

uniform ivec2 _TexSize;
uniform ivec3 _WorldSize;
uniform vec3 _WorldPos;
uniform vec3 _BrushPos;

// 0 = calc overall size, 1 = actually compute vertices
uniform uint _Mode;

const uint VertCount = 6;
const int Bands = 10;
const int VertexMapLength = 28;
const int VertexLookupLength0 = 15;
const int VertexLookupLength1 = 48;


/**
* Maps the height number into the corresponding VertexLookup, see
* https://www.boristhebrave.com/2021/12/29/2d-marching-cubes-with-multiple-colors/
*/
const int VertexMap[] =
{
    // index and resulting mapping (-1 => no matching combination)
    //0, 1,  2,  3, 4, 5, 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
      0, 1, -1, -1, 2, 3, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1,  5,  6,  7, -1,  8,  9, 10, -1, 11, 12, 13, 14
};


/** 
 * indices to vertices arranged in a plane
 * 0--4/8--1
 * |       |
 * 5/9-X---6/10
 * |       |
 * 2--7/11-3
 * where x is 12, 13, 14, 15
 * Index dictates the height lookup in VertexToWorld
 * Connecting triples into triangles results in the actual mesh part
 * Note: flattened into 1D!
 */
const int VertexLookup[] =
{
    0, 1, 2, 1, 3, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 1, 2, 1, 6, 7, 7, 2, 1, 6, 11, 7, 6, 10, 11, 10, 3, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 1, 3, 0, 11, 5, 0, 3, 11, 7, 9, 11, 5, 11, 9, 9, 7, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 1, 5, 1, 6, 5, 5, 10, 9, 6, 10, 5, 9, 10, 2, 2, 10, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 1, 5, 1, 6, 5, 5, 12, 9, 12, 14, 9, 12, 6, 15, 6, 10, 15, 9, 14, 7, 7, 2, 9, 15, 10, 3, 3, 11, 15, 15, 14, 7, 7, 11, 15, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 3, 2, 0, 4, 10, 10, 3, 0, 4, 8, 6, 6, 10, 4, 8, 1, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 7, 7, 2, 0, 4, 8, 11, 11, 7, 4, 8, 1, 3, 3, 11, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 7, 7, 2, 0, 4, 8, 13, 13, 12, 4, 14, 15, 11, 11, 7, 14, 15, 10, 3, 3, 11, 15, 8, 1, 6, 6, 13, 8, 13, 6, 10, 10, 15, 13, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 5, 4, 8, 9, 9, 5, 4, 8, 1, 6, 7, 2, 9, 9, 8, 6, 6, 7, 9, 7, 6, 10, 10, 11, 7, 10, 3, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 5, 4, 8, 9, 9, 5, 4, 8, 1, 6, 8, 6, 7, 7, 9, 8, 9, 7, 2, 10, 3, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 5, 4, 8, 9, 9, 5, 4, 8, 1, 6, 7, 2, 9, 9, 8, 6, 6, 7, 9, 7, 6, 10, 10, 11, 7, 10, 3, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 5, 4, 10, 11, 11, 5, 4, 10, 3, 11, 4, 8, 6, 6, 10, 4, 5, 11, 7, 7, 9, 5, 9, 7, 2, 8, 1, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    8, 1, 3, 3, 11, 8, 4, 8, 13, 13, 12, 4, 14, 15, 11, 11, 7, 14, 0, 4, 12, 12, 5, 0, 9, 14, 7, 7, 2, 9, 5, 12, 14, 14, 9, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    9, 10, 3, 3, 2, 9, 5, 9, 14, 14, 12, 5, 15, 10, 6, 6, 13, 15, 0, 4, 12, 12, 5, 0, 8, 1, 6, 6, 13, 8, 4, 8, 13, 13, 12, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, 4, 12, 12, 5, 0, 8, 1, 6, 6, 13, 8, 15, 10, 3, 3, 11, 15, 7, 2, 9, 9, 14, 7, 9, 5, 12, 12, 14, 9, 4, 8, 13, 13, 12, 4, 13, 6, 10, 10, 15, 13, 11, 7, 14, 14, 15, 11
};


/**
 * Actual world position for each vertex
 * contains {Xpos, ZPos, HeightLookup}
 * Note: flattened into 1d
 */
const float VertexToWorld[48] = {
    // regular points
    0.0, 1.0, 0.0,
    1.0, 1.0, 1.0,
    0.0, 0.0, 2.0,
    1.0, 0.0, 3.0,
    // in between, first 
    0.5, 1.0, 0.0,
    0.0, 0.5, 0.0,
    1.0, 0.5, 1.0,
    0.5, 0.0, 2.0,
    // in between, last
    0.5, 1.0, 1.0,
    0.0, 0.5, 2.0,
    1.0, 0.5, 3.0,
    0.5, 0.0, 3.0,
    // center for vertex 0, 1, 2, 3
    0.5, 0.5, 0.0,
    0.5, 0.5, 1.0,
    0.5, 0.5, 2.0,
    0.5, 0.5, 3.0
};

int GetHeightID(int Heights[4]){
    int HeightMap[Bands];
    for (int i = 0; i < Bands; i++){
        HeightMap[i] = -1;
    }

    int CurIndex = 0;
    if (HeightMap[Heights[0]] < 0){
        HeightMap[Heights[0]] = CurIndex;
        CurIndex++;
    }
    if (HeightMap[Heights[1]] < 0){
        HeightMap[Heights[1]] = CurIndex;
        CurIndex++;
    }
    if (HeightMap[Heights[2]] < 0){
        HeightMap[Heights[2]] = CurIndex;
        CurIndex++;
    }
    if (HeightMap[Heights[3]] < 0){
        HeightMap[Heights[3]] = CurIndex;
        CurIndex++;
    }

    // heightMap[0] is always 0!
    int HeightID = HeightMap[Heights[3]] + HeightMap[Heights[2]] * 4 + HeightMap[Heights[1]] * 16;
    return HeightID;
}

/** Uses height interpolation to calculate the resulting WorldPos*/
vec3 GetVertex(int Index, int Heights[4])
{
    int Start = Index * 3;
    vec3 Tmp = vec3(
        VertexToWorld[Start],
        Heights[int(VertexToWorld[Start + 2])],
        VertexToWorld[Start + 1]
    );
    return Tmp;
}

void GenerateTriangles(ivec3 id, int Heights[4], int Start, int End){
    // read the info from the data struct to fill in triangles
    for (int i = Start; i < End; i += 3)
    {
        if (VertexLookup[i] == -1)
            break;

        vec3 A = GetVertex(VertexLookup[i + 0], Heights) + id;
        vec3 B = GetVertex(VertexLookup[i + 1], Heights) + id;
        vec3 C = GetVertex(VertexLookup[i + 2], Heights) + id;
        // scale back down to 1x1x1
        A.y = A.y / (Bands - 2) * _WorldSize.y;
        B.y = B.y / (Bands - 2) * _WorldSize.y;
        C.y = C.y / (Bands - 2) * _WorldSize.y;
        A.xz = A.xz / _TexSize * _WorldSize.xz;
        B.xz = B.xz / _TexSize * _WorldSize.xz;
        C.xz = C.xz / _TexSize * _WorldSize.xz;
        A += _WorldPos;
        B += _WorldPos;
        C += _WorldPos;

        // each triangle has 3 vertices and only 1 normal
        uint Index = atomicAdd(Counter.Count, 3);
        Positions.Entries[Index + 0].xyz = A;
        Positions.Entries[Index + 1].xyz = B;
        Positions.Entries[Index + 2].xyz = C;
        Normals.Entries[Index / 3].xyz = normalize(cross(normalize(A - B), normalize(C - B)));
    }
}

void CountTriangles(ivec3 id, int Heights[4], int Start, int End){
    // to have quick lookup we pad the data with -1 for invalid entries
    // this allows for "jump to entry x", since each have the same length.
    // But: we now need to count how many entries we actually need to avoid a largely empty buffer
    for (int i = Start; i < End; i += 3)
    {
        if (VertexLookup[i] == -1)
            break;

        atomicAdd(Counter.Count, 3);
    }
}

void GenerateHeightMesh(ivec3 id){
    if (_Mode != MODE_COUNT_TRIANGLES && _Mode != MODE_GENERATE_TRIANGLES)
        return;
    // height indicates the type of mesh via lookup table
    // clamped to different height bands

    // reading out of bounds will produce undefined (0), even if we set tex mode Clamp
    int ClampW = _TexSize.x - 1;
    int ClampH = _TexSize.y - 1;
    ivec2 Offset0 = ivec2(clamp(id.x + 0, 0, ClampW), clamp(id.z + 1, 0, ClampH));
    ivec2 Offset1 = ivec2(clamp(id.x + 1, 0, ClampW), clamp(id.z + 1, 0, ClampH));
    ivec2 Offset2 = ivec2(clamp(id.x + 0, 0, ClampW), clamp(id.z + 0, 0, ClampH));
    ivec2 Offset3 = ivec2(clamp(id.x + 1, 0, ClampW), clamp(id.z + 0, 0, ClampH));
    int Height0 = int(imageLoad(Result, Offset0).r * (Bands - 1));
    int Height1 = int(imageLoad(Result, Offset1).r * (Bands - 1));
    int Height2 = int(imageLoad(Result, Offset2).r * (Bands - 1));
    int Height3 = int(imageLoad(Result, Offset3).r * (Bands - 1));

    int Heights[4] = { Height0, Height1, Height2, Height3 };
    int HeightID = GetHeightID(Heights);
    if (HeightID >= VertexMapLength)
        return;

    int LookupID = VertexMap[HeightID];
    if (LookupID < 0 || LookupID >= VertexLookupLength0)
        return;

    // lookup the blueprint for the structure
    int Start = LookupID * VertexLookupLength1;
    int End = (LookupID + 1) * VertexLookupLength1;
    if (_Mode == MODE_COUNT_TRIANGLES){
        CountTriangles(id, Heights, Start, End);
    }else if (_Mode == MODE_GENERATE_TRIANGLES){
        GenerateTriangles(id, Heights, Start, End);
    }
}

void ApplySelection(ivec3 id){
    if (_Mode != MODE_APPLY_SELECTION)
        return;
    
    int BrushSize = 5;
    vec2 BrushUV = (_BrushPos.xz - _WorldPos.xz) / _WorldSize.xz * _TexSize;
    vec2 diff = BrushUV - id.xz;
    float dist2 = dot(diff, diff);
    float d = 1 - dist2 / (BrushSize * BrushSize);
    uint GlobalIndex = id.z * _TexSize.x + id.x;
    Selection.Entries[GlobalIndex] = uint(d * 256);
}

void GenerateTex(ivec3 id){
    if (_Mode != MODE_GENERATE_TEX)
        return;
    
    imageStore(Result, id.xz, vec4(_Mode, 0, 0, 1));
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.x, 0, gl_GlobalInvocationID.y);
    
    GenerateTex(id);
    GenerateHeightMesh(id);
    ApplySelection(id);
}