#version 430 
/** 
 * Shader that creates a 2D marching cube terrain mesh from a 1d height buffer
 * Execution order is as follows:
 * 1) Look at each height point and determine the amount of vertices needed
 * 2) prefix-sum to get actual write offset
 * 3) Reserve buffer with appropriate size (CPU)
 * 4) Write vertices into buffer
 * 5) Write normals into buffer
 */

/**
 * Multi-modal Shader either:
 * - creating a heightmap
 * - creating a mesh according to the heightmap
 */
#define MODE_COUNT_TRIANGLES 0
#define MODE_GENERATE_TRIANGLES 1
#define MODE_RESET_HEIGHT 2
#define MODE_PREFIXSUM_OFFSET 3

#include "TERRAIN_COMMON_SHADER"

#define DISPATCH_SIZE 2
layout(local_size_x = DISPATCH_SIZE, local_size_y = DISPATCH_SIZE) in;

/** 
 * Contains triangle vertices for all points in the height map
 * Each point creates 4 quads (consisting of 2 triangles each), with following Order (and order in each quad):
 *      * ------*------ *    0/3    *---*     1/2     *---*
 *      |   0   |   1   |    quads: | 0/|     quads:  |\ 0|
 *      * ------*------ *           | / |             | \ |
 *      |   2   |   3   |           |/ 1|             |1 \|
 *      * ------*------ *           *---*             *---*
 * Note that the triangles are arranged differently for quads 0/3 and 1/2, as the have to build a square in the middle!
 * Since each quad can have different heights, we might need additional vertical quads, which are added after all regular quads
 * This leads to different sizes in memory depending on vertical quad amount, see PositionOffsetBuffer
 **/
layout(std430, binding = SSBO_LAYOUT_VERTICES) buffer VertexBuffer {
    vec4 Entries[];
} Vertices;

layout(std430, binding = SSBO_LAYOUT_NORMALS) buffer NormalBuffer {
    vec4 Entries[];
} Normals;

/** 
 * Contains all necessary information to calculate the actual terrain mesh from. 
 * Convenient cause we only need to save this and then can easily re-generate everything
 * Layout:
 * 0 - Selection bit mask
 * 1..23 - unused
 * 24..31 - actual height info
 */
layout(std430, binding = SSBO_LAYOUT_HEIGHTS) buffer HeightBuffer {
    uint Value[];
} Heights;

/** 
 * Stores the prefixsummed offset of the first triangle of each height point
 * This can be different, depending on the amount of vertical slices!
 * Note: will have just the base amount of triangles in the first iteration
 */
layout(std430, binding = SSBO_LAYOUT_VERTEX_OFFSETS) buffer VertexOffsetsBuffer {
    uint Values[];
} VertexOffsets;

/** 
 * indices to vertices arranged in a plane
 * 0--4/8--1
 * |       |
 * 5/9-X---6/10
 * |       |
 * 2--7/11-3
 * where x is 12, 13, 14, 15
 * Index dictates the height lookup in VertexToWorld
 * Connecting triples into triangles results in the actual mesh part
 * Note: Will be filled by @TerrainManager
 */
layout(std430, binding = SSBO_LAYOUT_VERTICAL_QUADS) readonly buffer VerticalQuadBuffer {
    int Values[15][24];
} VerticalQuadLookup;

/** Buffer that contains the actual length of each of the @VerticalQuadLookup entries */
layout(std430, binding = SSBO_LAYOUT_VERTICAL_QUAD_LENGTHS) readonly buffer VerticalQuadLengthBuffer {
    int Values[15];
} VerticalQuadLength;

/** 
 * Buffer containing the base vertices that every point will have
 * Same indexing as VerticalQuadLookup, though each vertex row is way more similar
 */
layout(std430, binding = SSBO_LAYOUT_HORIZONTAL_QUADS) readonly buffer HorizontalQuadBuffer {
    int Values[15][24];
} HorizontalQuadLookup;

/** Small buffer that is used to copy the overall size back to the CPU*/
layout(std430, binding = SSBO_LAYOUT_COUNT) buffer CountBuffer {
    uint Value;
} Count;


uniform ivec2 _TexSize;
uniform ivec3 _WorldSize;
uniform vec3 _WorldPos;
uniform vec3 _BrushPos;
uniform int VertexLookupLength0;
uniform int VertexLookupLength1;

// 0 = calc overall size, 1 = actually compute vertices
uniform uint _Mode;

const uint VertCount = 6;
const int VertexMapLength = 28;


/**
* Maps the height number into the corresponding VertexLookup, see
* https://www.boristhebrave.com/2021/12/29/2d-marching-cubes-with-multiple-colors/
* Note: this is not the exact same ordering, as we count our vertices in a different order
* Some pairs are swapped
*/
const int VertexMap[] =
{
    // index and resulting mapping (-1 => no matching combination)
    //0, 1,  2,  3, 4, 5, 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
      0, 1, -1, -1, 2, 3, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1,  9,  8, 10, -1,  6,  5,  7, -1, 12, 11, 13, 14
};




/**
 * Actual world position for each vertex
 * contains {Xpos, ZPos, HeightLookup}
 * Note: flattened into 1d
 */
const float VertexToWorld[48] = {
    // regular points
    0.0, 0.0, 0.0,
    1.0, 0.0, 1.0,
    0.0, 1.0, 2.0,
    1.0, 1.0, 3.0,
    // in between, first (height is dependent on "lower" vertex)
    0.5, 0.0, 0.0,
    0.0, 0.5, 0.0,
    1.0, 0.5, 1.0,
    0.5, 1.0, 2.0,
    // in between, last (height is dependent on "higher" vertex)
    0.5, 0.0, 1.0,
    0.0, 0.5, 2.0,
    1.0, 0.5, 3.0,
    0.5, 1.0, 3.0,
    // center for vertex 0, 1, 2, 3
    0.5, 0.5, 0.0,
    0.5, 0.5, 1.0,
    0.5, 0.5, 2.0,
    0.5, 0.5, 3.0
};

int GetHeightID(int Heights[4]){
    int HeightMap[MAX_VALUE];
    for (int i = 0; i < MAX_VALUE; i++){
        HeightMap[i] = -1;
    }

    int CurIndex = 0;
    if (HeightMap[Heights[0]] < 0){
        HeightMap[Heights[0]] = CurIndex;
        CurIndex++;
    }
    if (HeightMap[Heights[1]] < 0){
        HeightMap[Heights[1]] = CurIndex;
        CurIndex++;
    }
    if (HeightMap[Heights[2]] < 0){
        HeightMap[Heights[2]] = CurIndex;
        CurIndex++;
    }
    if (HeightMap[Heights[3]] < 0){
        HeightMap[Heights[3]] = CurIndex;
        CurIndex++;
    }

    // heightMap[0] is always 0!
    int HeightID = HeightMap[Heights[3]] + HeightMap[Heights[2]] * 4 + HeightMap[Heights[1]] * 16;
    return HeightID;
}

/** Uses height interpolation to calculate the resulting WorldPos*/
vec3 GetVertex(int Index, int Heights[4])
{
    // points into a collection of vec3
    int Start = Index * 3; 
    vec3 Tmp = vec3(
        VertexToWorld[Start],
        Heights[int(VertexToWorld[Start + 2])],
        VertexToWorld[Start + 1]
    );
    return Tmp;
}

int GetHeightIndexFor(ivec3 id, ivec2 Offset){
    return clamp(id.z + Offset.y, 0, _TexSize.y - 1) * _TexSize.x + clamp(id.x + Offset.x, 0, _TexSize.x - 1);
}

int GetHeightForIndex(int Index){
    return clamp(int(Heights.Value[Index] & LAYOUT_HEIGHT_MASK), 0, MAX_VALUE - 1);
}

void WriteTriangle(vec3 A, vec3 B, vec3 C, uint Index){
    // scale back down to 1x1x1, then move to appropriate world space
    A.y = A.y / (MAX_VALUE - 2) * _WorldSize.y;
    B.y = B.y / (MAX_VALUE - 2) * _WorldSize.y;
    C.y = C.y / (MAX_VALUE - 2) * _WorldSize.y;
    A.xz = A.xz / _TexSize * _WorldSize.xz;
    B.xz = B.xz / _TexSize * _WorldSize.xz;
    C.xz = C.xz / _TexSize * _WorldSize.xz;
    A += _WorldPos;
    B += _WorldPos;
    C += _WorldPos;
    
    Vertices.Entries[Index + 0].xyz = A;
    Vertices.Entries[Index + 1].xyz = B;
    Vertices.Entries[Index + 2].xyz = C;
    Normals.Entries[Index / 3].xyz = normalize(cross(normalize(A - B), normalize(C - B)));
}

void GenerateTriangles(ivec3 id, int Heights[4], int Combination){
    // since each point has the base horizontal quads we can just fill them,
    // based on the precomputed count (offset by one)
    uint Index = GetHeightIndexFor(id, ivec2(0));
    uint TargetStart = Index == 0 ? 0 : VertexOffsets.Values[Index - 1];
    
    for (uint i = 0; i < VertexLookupLength1; i += 3){
        vec3 A = GetVertex(HorizontalQuadLookup.Values[Combination][i + 0], Heights) + id;
        vec3 B = GetVertex(HorizontalQuadLookup.Values[Combination][i + 1], Heights) + id;
        vec3 C = GetVertex(HorizontalQuadLookup.Values[Combination][i + 2], Heights) + id;
        WriteTriangle(A, B, C, TargetStart + i);
    }
    
    // now we can add the specific vertical quads
    // we should have enough space in our buffer since we precomputed its size
    int VerticalLength = VerticalQuadLength.Values[Combination];
    for (uint i = 0; i < VerticalLength; i += 3)
    {
        if (VerticalQuadLookup.Values[Combination][i] == -1)
            break;

        vec3 A = GetVertex(VerticalQuadLookup.Values[Combination][i + 0], Heights) + id;
        vec3 B = GetVertex(VerticalQuadLookup.Values[Combination][i + 1], Heights) + id;
        vec3 C = GetVertex(VerticalQuadLookup.Values[Combination][i + 2], Heights) + id;
        // draw twice to avoid backface culling depending on height
        WriteTriangle(A, B, C, TargetStart + VertexLookupLength1 + i * 2 + 0);
        WriteTriangle(A, C, B, TargetStart + VertexLookupLength1 + i * 2 + 3);
    }
}

void CountTriangles(ivec3 id, int Heights[4], int Combination){
    // to have quick lookup we pad the data with -1 for invalid entries
    // this allows for "jump to entry x", since each have the same length.
    // we overcome the "oh now i have to count each entry" by precomputing
    // note: we need to render vertical once twice to avoid backfacee culling
    int Index = GetHeightIndexFor(id, ivec2(0));
    VertexOffsets.Values[Index] = VertexLookupLength1 + VerticalQuadLength.Values[Combination] * 2;
}

void GenerateHeightMesh(ivec3 id){
    if (_Mode != MODE_COUNT_TRIANGLES && _Mode != MODE_GENERATE_TRIANGLES)
        return;
    
    // height indicates the type of mesh via lookup table
    // clamped to different height "bands"
    int Index0 = GetHeightIndexFor(id, ivec2(0, 0));
    int Index1 = GetHeightIndexFor(id, ivec2(1, 0));
    int Index2 = GetHeightIndexFor(id, ivec2(0, 1));
    int Index3 = GetHeightIndexFor(id, ivec2(1, 1));
    
    int Height0 = GetHeightForIndex(Index0);
    int Height1 = GetHeightForIndex(Index1);
    int Height2 = GetHeightForIndex(Index2);
    int Height3 = GetHeightForIndex(Index3);
        
    int Heights[4] = { Height0, Height1, Height2, Height3 };
    int HeightID = GetHeightID(Heights);
    if (HeightID >= VertexMapLength)
        return;

    int LookupID = VertexMap[HeightID];
    if (LookupID < 0 || LookupID >= VertexLookupLength0)
        return;

    // lookup the blueprint for the structure
    if (_Mode == MODE_COUNT_TRIANGLES){
        CountTriangles(id, Heights, LookupID);
    }else if (_Mode == MODE_GENERATE_TRIANGLES){
        GenerateTriangles(id, Heights, LookupID);
    }
}

void GenerateTex(ivec3 id){
    if (_Mode != MODE_RESET_HEIGHT)
        return;

    uint GlobalIndex = id.z * _TexSize.x + id.x;
    Heights.Value[GlobalIndex] = 0;
    Heights.Value[GlobalIndex] |= (1 << LAYOUT_GRASS);
}

// this is not really efficient and is only used as we dont want to transmit the data between GPU/CPU
// TODO: make parallel
void PrefixSumOffset(ivec3 id){
    if (_Mode != MODE_PREFIXSUM_OFFSET)
        return;
    
    if (id.x != 0 || id.y != 0 || id.z != 0)
        return;
    
    uint Max = _TexSize.x * _TexSize.y;
    for (uint i = 1; i < Max; i++){
        VertexOffsets.Values[i] = VertexOffsets.Values[i] + VertexOffsets.Values[i - 1];
    }
    Count.Value = VertexOffsets.Values[Max - 1];
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.x, 0, gl_GlobalInvocationID.y);

    GenerateTex(id);
    PrefixSumOffset(id);
    GenerateHeightMesh(id);
}