
#define MAX_VALUE 10
#define LAYOUT_SELECTION 31
#define LAYOUT_TEX0 (LAYOUT_SELECTION - 1)
#define LAYOUT_TEX1 (LAYOUT_TEX0 - 1)
#define LAYOUT_TEX2 (LAYOUT_TEX1 - 1)
#define LAYOUT_GRASS (LAYOUT_TEX2 - 1)
#define LAYOUT_FLOWER (LAYOUT_GRASS - 1)

#define LAYOUT_HEIGHT_MASK 0xFFu

#define DECORATION_TYPE_COUNT 2
#define DECORATION_CHANCE_GRASS 1
#define DECORATION_CHANCE_FLOWER 0.3
#define DECORATION_GRASS 1
#define DECORATION_FLOWER 2
