
#define MAX_VALUE 10
#define LAYOUT_SELECTION 31
#define LAYOUT_TEX0 (LAYOUT_SELECTION - 1)
#define LAYOUT_TEX1 (LAYOUT_TEX0 - 1)
#define LAYOUT_TEX2 (LAYOUT_TEX1 - 1)


#define LAYOUT_HEIGHT_MASK 0xFFu

