#version 430 
layout(local_size_x = 8, local_size_y = 8) in; 

layout(std430, binding = 0) buffer PositionBuffer {
    vec3 data[]; 
};
layout(binding = 1, rgba16f) uniform image2D Result;
//layout(binding = 2, rgba16f) uniform image2D Preview;

uniform ivec2 _TexSize;
uniform ivec3 _WorldSize;
uniform ivec3 _WorldPos;

const uint VertCount = 6;

void GenerateBaseMesh(ivec3 id){
    int Index = id.y * _TexSize.x + id.x;
    data[Index * VertCount + 0] = vec3(0 + id.x, 0, 0 + id.y) / vec3(_TexSize.x, 1, _TexSize.y) * _WorldSize + _WorldPos;
    data[Index * VertCount + 1] = vec3(0 + id.x, 0, 1 + id.y) / vec3(_TexSize.x, 1, _TexSize.y) * _WorldSize + _WorldPos;
    data[Index * VertCount + 2] = vec3(1 + id.x, 0, 0 + id.y) / vec3(_TexSize.x, 1, _TexSize.y) * _WorldSize + _WorldPos;
    data[Index * VertCount + 3] = vec3(1 + id.x, 0, 0 + id.y) / vec3(_TexSize.x, 1, _TexSize.y) * _WorldSize + _WorldPos;
    data[Index * VertCount + 4] = vec3(0 + id.x, 0, 1 + id.y) / vec3(_TexSize.x, 1, _TexSize.y) * _WorldSize + _WorldPos;
    data[Index * VertCount + 5] = vec3(1 + id.x, 0, 1 + id.y) / vec3(_TexSize.x, 1, _TexSize.y) * _WorldSize + _WorldPos;
}

void main() { 
    ivec2 UV = ivec2(gl_GlobalInvocationID.xy); 
    imageStore(Result, UV, vec4(0, 1, 0, 1));
}