#version 430 

/**
 * Shader updating the selection mask for terrain modifications
 * Compares mouse input with buffer index mapped to world position
 */
#define DISPATCH_SIZE 2
layout(local_size_x = DISPATCH_SIZE, local_size_y = DISPATCH_SIZE) in;


#include "TERRAIN_COMMON_SHADER"

// for more layout info seee terrainmesh shader
layout(std430, binding = SSBO_LAYOUT_HEIGHTS) buffer HeightBuffer {
    uint Value[]; 
} Heights;

#define MODE_CLEAR 0
#define MODE_SELECT 1
#define MODE_DESELECT 2

#define TARGET_SELECTION 0
#define TARGET_TEX0 1
#define TARGET_TEX1 2
#define TARGET_TEX2 3
#define TARGET_GRASS 4
#define TARGET_FLOWER 5

/** Stores calculation by mode in an easy lookup table*/
const uint LayoutByTarget[] = uint[](
    LAYOUT_SELECTION,   
    LAYOUT_TEX0,         
    LAYOUT_TEX1,         
    LAYOUT_TEX2,
    LAYOUT_GRASS,
    LAYOUT_FLOWER         
);

const bool EqualByTarget[] = bool[](
    true,       //LAYOUT_SELECTION,
    false,      //LAYOUT_TEX0,     
    false,      //LAYOUT_TEX1,     
    false,      //LAYOUT_TEX2      
    false,      //LAYOUT_GRASS      
    false       //LAYOUT_FLOWER      
);

uniform ivec2 _TexSize;
uniform ivec3 _WorldSize;
uniform vec3 _WorldPos;
uniform vec3 _StartWorldPos;
uniform vec3 _BrushPos;
uniform uint _BrushSize;
uniform uint _Mode;
uniform uint _Target;

void ApplySelection(ivec3 id){
    uint GlobalIndex = id.z * _TexSize.x + id.x;
    uint TargetLayout = LayoutByTarget[_Target];
    
    // use the mouse pos as origin, distance to it as falloff value
    vec2 BrushUV = (_BrushPos.xz - _WorldPos.xz) / _WorldSize.xz * _TexSize;
    vec2 Diff = BrushUV - id.xz;
    float DistSqr = dot(Diff, Diff);
    float DistNorm = 1 - DistSqr / (_BrushSize * _BrushSize);
    DistNorm = clamp(round(DistNorm), 0, 1);
    uint NewValue = uint(DistNorm) << TargetLayout;

    // can only add to selection if the current height is the same 
    // as the first selected height (to make managing plateaus easier)
    vec2 OriginalUV = (_StartWorldPos.xz - _WorldPos.xz) / _WorldSize.xz * _TexSize;
    uint OriginalIndex = uint(OriginalUV.y) * _TexSize.x + uint(OriginalUV.x);
    uint OriginalHeight = Heights.Value[OriginalIndex] & LAYOUT_HEIGHT_MASK;
    uint Height = Heights.Value[GlobalIndex] & LAYOUT_HEIGHT_MASK;
    
    bool bIsEqual = !EqualByTarget[_Target] || (OriginalHeight == Height);
    uint OldValue = Heights.Value[GlobalIndex];
    NewValue = bIsEqual ? NewValue : 0;
    uint ClearMask = ~(1 << TargetLayout);
    uint Value =
        _Mode == MODE_CLEAR ? (ClearMask & OldValue) :
        _Mode == MODE_SELECT ? (NewValue | OldValue) : 
        _Mode == MODE_DESELECT ? ((~NewValue) & OldValue) : 0;
    
    Heights.Value[GlobalIndex] = Value;
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.x, 0, gl_GlobalInvocationID.y);
    ApplySelection(id);
}