/** Provides shared layout information regarding the Height uint */
#define MAX_VALUE 10
#define LAYOUT_SELECTION 31
#define LAYOUT_TEX0 (LAYOUT_SELECTION - 1)
#define LAYOUT_TEX1 (LAYOUT_TEX0 - 1)
#define LAYOUT_TEX2 (LAYOUT_TEX1 - 1)
#define LAYOUT_GRASS (LAYOUT_TEX2 - 1)
#define LAYOUT_FLOWER (LAYOUT_GRASS - 1)

#define LAYOUT_HEIGHT_MASK 0xFFu

#define DECORATION_TYPE_COUNT 2
#define DECORATION_CHANCE_GRASS 1
#define DECORATION_CHANCE_FLOWER 0.3
#define DECORATION_GRASS 1
#define DECORATION_FLOWER 2

/** SSBO bindings, have to be the same as @TerrainSSBO! */
#define SSBO_LAYOUT_VERTICES 0
#define SSBO_LAYOUT_NORMALS 1
#define SSBO_LAYOUT_HEIGHTS 2
#define SSBO_LAYOUT_VERTEX_OFFSETS 3
#define SSBO_LAYOUT_VERTICAL_QUADS 4
#define SSBO_LAYOUT_VERTICAL_QUAD_LENGTHS 5
#define SSBO_LAYOUT_HORIZONTAL_QUADS 6
#define SSBO_LAYOUT_COUNT 7
#define SSBO_LAYOUT_POSITIONS 8
